# Generated by Django 4.1.2 on 2022-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camionetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
