# Generated by Django 4.1.2 on 2022-12-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamionetas', '0002_alter_camionetas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionetas',
            name='anio_fabricacion',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
