# Generated by Django 4.1.2 on 2022-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamionetas', '0003_camionetas_anio_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='anio_fabricacion',
            field=models.DateField(),
        ),
    ]
