# Generated by Django 4.1.2 on 2022-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamionetas', '0004_alter_camionetas_anio_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='anio_fabricacion',
            field=models.IntegerField(),
        ),
    ]
