# Generated by Django 4.1.2 on 2022-12-18 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamionetas', '0005_alter_camionetas_anio_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camionetas',
            name='fecha_publiacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
