# Generated by Django 4.1.4 on 2022-12-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCamionetas', '0006_camionetas_fecha_publiacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camionetas',
            name='fecha_publiacion',
            field=models.DateField(help_text='AAAA-MM-DD'),
        ),
    ]
