# Generated by Django 4.1.4 on 2022-12-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutosDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('kilometros', models.IntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='Fotos')),
            ],
        ),
    ]
