# Generated by Django 4.1.4 on 2022-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAutos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearAnuncioDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('kilometros', models.IntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='Fotos')),
            ],
        ),
        migrations.DeleteModel(
            name='AutosDB',
        ),
    ]
